/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
    "AgentRelayCloudWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AppDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "AuthSessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BrokerKeySecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "CredentialEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DaytonaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayauthInternalSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayfileInternalHmacSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SandboxStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WorkflowStorage": {
      "bucketName": string
      "stsRoleArn": string
      "type": "sst.sst.Linkable"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "RelayauthApi": cloudflare.Service
    "RelayauthDatabase": cloudflare.D1Database
    "RelayauthKv": cloudflare.KVNamespace
    "RelaycronApi": cloudflare.Service
    "RelaycronDatabase": cloudflare.D1Database
    "RelayfileApi": cloudflare.Service
    "RelayfileCleanupHandler": cloudflare.Service
    "RelayfileContentBucket": cloudflare.R2Bucket
    "RelayfileDatabase": cloudflare.D1Database
    "RelayfileEnvelopeDlq": cloudflare.Queue
    "RelayfileEnvelopeQueue": cloudflare.Queue
    "RelayfileKv": cloudflare.KVNamespace
    "RelayfileWritebackQueue": cloudflare.Queue
  }
}

import "sst"
export {}