// Generated by scripts/generate-nango-linear-query-fragments.mjs from
// @relayfile/adapter-linear/types LinearLabel (id, name, description, color, team, parent, createdAt, updatedAt). Do not edit by hand.
//
// Nango compile disallows non-allowlisted package imports, including
// @relayfile/adapter-linear. This generated relative module lets Linear syncs
// consume adapter-owned label shape without hand-maintained field fragments.
// archivedAt is a Linear lifecycle field required so archived labels stay
// materialized instead of leaving stale active records behind.
export const LINEAR_LABEL_FIELDS = `
        id
        name
        description
        color
        archivedAt
        createdAt
        updatedAt
        team {
          id
          key
          name
        }
        parent {
          id
          name
        }
`;
