// Generated by scripts/generate-nango-provider-registry.mjs.
// Do not edit by hand. The source of truth is nango-integrations/.nango/nango.json.

export const GENERATED_NANGO_PROVIDER_MODEL_REGISTRY = [
  {
    "key": "github-relay:fetch-repos:Repo",
    "provider": "github-relay",
    "sync": "fetch-repos",
    "model": "Repo"
  },
  {
    "key": "github-relay:fetch-open-prs:PullRequest",
    "provider": "github-relay",
    "sync": "fetch-open-prs",
    "model": "PullRequest"
  },
  {
    "key": "github-relay:fetch-open-issues:Issue",
    "provider": "github-relay",
    "sync": "fetch-open-issues",
    "model": "Issue"
  },
  {
    "key": "slack-relay:fetch-channel-history:SlackMessage",
    "provider": "slack-relay",
    "sync": "fetch-channel-history",
    "model": "SlackMessage"
  },
  {
    "key": "slack-relay:fetch-users:SlackUser",
    "provider": "slack-relay",
    "sync": "fetch-users",
    "model": "SlackUser"
  },
  {
    "key": "slack-relay:fetch-channels:SlackChannel",
    "provider": "slack-relay",
    "sync": "fetch-channels",
    "model": "SlackChannel"
  },
  {
    "key": "telegram-relay:fetch-bot-config:TelegramBotConfig",
    "provider": "telegram-relay",
    "sync": "fetch-bot-config",
    "model": "TelegramBotConfig"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramUpdate",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramUpdate"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramChat",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramChat"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramMessage",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramMessage"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramCallbackQuery",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramCallbackQuery"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramInlineQuery",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramInlineQuery"
  },
  {
    "key": "telegram-relay:fetch-updates:TelegramReaction",
    "provider": "telegram-relay",
    "sync": "fetch-updates",
    "model": "TelegramReaction"
  },
  {
    "key": "notion-relay:fetch-pages:NotionPage",
    "provider": "notion-relay",
    "sync": "fetch-pages",
    "model": "NotionPage"
  },
  {
    "key": "notion-relay:fetch-pages:NotionPageContent",
    "provider": "notion-relay",
    "sync": "fetch-pages",
    "model": "NotionPageContent"
  },
  {
    "key": "notion-relay:fetch-databases:NotionDatabase",
    "provider": "notion-relay",
    "sync": "fetch-databases",
    "model": "NotionDatabase"
  },
  {
    "key": "notion-relay:fetch-users:NotionUser",
    "provider": "notion-relay",
    "sync": "fetch-users",
    "model": "NotionUser"
  },
  {
    "key": "linear-relay:fetch-active-issues:LinearIssue",
    "provider": "linear-relay",
    "sync": "fetch-active-issues",
    "model": "LinearIssue"
  },
  {
    "key": "linear-relay:fetch-comments:LinearComment",
    "provider": "linear-relay",
    "sync": "fetch-comments",
    "model": "LinearComment"
  },
  {
    "key": "linear-relay:fetch-labels:LinearLabel",
    "provider": "linear-relay",
    "sync": "fetch-labels",
    "model": "LinearLabel"
  },
  {
    "key": "linear-relay:fetch-users:LinearUser",
    "provider": "linear-relay",
    "sync": "fetch-users",
    "model": "LinearUser"
  },
  {
    "key": "linear-relay:fetch-teams:LinearTeam",
    "provider": "linear-relay",
    "sync": "fetch-teams",
    "model": "LinearTeam"
  },
  {
    "key": "linear-relay:fetch-projects:LinearProject",
    "provider": "linear-relay",
    "sync": "fetch-projects",
    "model": "LinearProject"
  },
  {
    "key": "linear-relay:fetch-milestones:LinearMilestone",
    "provider": "linear-relay",
    "sync": "fetch-milestones",
    "model": "LinearMilestone"
  },
  {
    "key": "linear-relay:fetch-roadmaps:LinearRoadmap",
    "provider": "linear-relay",
    "sync": "fetch-roadmaps",
    "model": "LinearRoadmap"
  },
  {
    "key": "linear-relay:fetch-cycles:LinearCycle",
    "provider": "linear-relay",
    "sync": "fetch-cycles",
    "model": "LinearCycle"
  },
  {
    "key": "linear-relay:states:LinearState",
    "provider": "linear-relay",
    "sync": "states",
    "model": "LinearState"
  },
  {
    "key": "confluence-relay:fetch-spaces:ConfluenceSpace",
    "provider": "confluence-relay",
    "sync": "fetch-spaces",
    "model": "ConfluenceSpace"
  },
  {
    "key": "confluence-relay:fetch-pages:ConfluencePage",
    "provider": "confluence-relay",
    "sync": "fetch-pages",
    "model": "ConfluencePage"
  },
  {
    "key": "jira-relay:fetch-projects:JiraProject",
    "provider": "jira-relay",
    "sync": "fetch-projects",
    "model": "JiraProject"
  },
  {
    "key": "jira-relay:fetch-issues:JiraIssue",
    "provider": "jira-relay",
    "sync": "fetch-issues",
    "model": "JiraIssue"
  },
  {
    "key": "jira-relay:fetch-sprints:JiraSprint",
    "provider": "jira-relay",
    "sync": "fetch-sprints",
    "model": "JiraSprint"
  },
  {
    "key": "gitlab-relay:fetch-projects:GitLabProject",
    "provider": "gitlab-relay",
    "sync": "fetch-projects",
    "model": "GitLabProject"
  },
  {
    "key": "gitlab-relay:fetch-merge-requests:GitLabMergeRequest",
    "provider": "gitlab-relay",
    "sync": "fetch-merge-requests",
    "model": "GitLabMergeRequest"
  },
  {
    "key": "gitlab-relay:fetch-issues:GitLabIssue",
    "provider": "gitlab-relay",
    "sync": "fetch-issues",
    "model": "GitLabIssue"
  },
  {
    "key": "gitlab-relay:fetch-commits:GitLabCommit",
    "provider": "gitlab-relay",
    "sync": "fetch-commits",
    "model": "GitLabCommit"
  },
  {
    "key": "gitlab-relay:fetch-pipelines:GitLabPipeline",
    "provider": "gitlab-relay",
    "sync": "fetch-pipelines",
    "model": "GitLabPipeline"
  },
  {
    "key": "gitlab-relay:fetch-pipelines:GitLabPipelineJob",
    "provider": "gitlab-relay",
    "sync": "fetch-pipelines",
    "model": "GitLabPipelineJob"
  },
  {
    "key": "gitlab-relay:fetch-deployments:GitLabDeployment",
    "provider": "gitlab-relay",
    "sync": "fetch-deployments",
    "model": "GitLabDeployment"
  },
  {
    "key": "gitlab-relay:fetch-tags:GitLabTag",
    "provider": "gitlab-relay",
    "sync": "fetch-tags",
    "model": "GitLabTag"
  },
  {
    "key": "x-relay:fetch-searches:XSearchBundle",
    "provider": "x-relay",
    "sync": "fetch-searches",
    "model": "XSearchBundle"
  },
  {
    "key": "google-mail-relay:fetch-labels:GoogleMailLabel",
    "provider": "google-mail-relay",
    "sync": "fetch-labels",
    "model": "GoogleMailLabel"
  },
  {
    "key": "google-mail-relay:fetch-filters:GoogleMailFilter",
    "provider": "google-mail-relay",
    "sync": "fetch-filters",
    "model": "GoogleMailFilter"
  },
  {
    "key": "google-mail-relay:fetch-send-as-aliases:GoogleMailSendAsAlias",
    "provider": "google-mail-relay",
    "sync": "fetch-send-as-aliases",
    "model": "GoogleMailSendAsAlias"
  },
  {
    "key": "google-mail-relay:fetch-messages:GoogleMailMessage",
    "provider": "google-mail-relay",
    "sync": "fetch-messages",
    "model": "GoogleMailMessage"
  },
  {
    "key": "google-mail-relay:fetch-threads:GoogleMailThread",
    "provider": "google-mail-relay",
    "sync": "fetch-threads",
    "model": "GoogleMailThread"
  },
  {
    "key": "google-mail-relay:renew-watch:GoogleMailWatchRenewal",
    "provider": "google-mail-relay",
    "sync": "renew-watch",
    "model": "GoogleMailWatchRenewal"
  },
  {
    "key": "google-calendar-relay:fetch-calendars:GoogleCalendar",
    "provider": "google-calendar-relay",
    "sync": "fetch-calendars",
    "model": "GoogleCalendar"
  },
  {
    "key": "google-calendar-relay:fetch-events:GoogleCalendarEvent",
    "provider": "google-calendar-relay",
    "sync": "fetch-events",
    "model": "GoogleCalendarEvent"
  },
  {
    "key": "google-calendar-relay:fetch-settings:GoogleCalendarSetting",
    "provider": "google-calendar-relay",
    "sync": "fetch-settings",
    "model": "GoogleCalendarSetting"
  },
  {
    "key": "google-calendar-relay:fetch-acls:GoogleCalendarAcl",
    "provider": "google-calendar-relay",
    "sync": "fetch-acls",
    "model": "GoogleCalendarAcl"
  },
  {
    "key": "google-calendar-relay:fetch-colors:GoogleCalendarColor",
    "provider": "google-calendar-relay",
    "sync": "fetch-colors",
    "model": "GoogleCalendarColor"
  },
  {
    "key": "google-calendar-relay:renew-watch:GoogleCalendarWatchRenewal",
    "provider": "google-calendar-relay",
    "sync": "renew-watch",
    "model": "GoogleCalendarWatchRenewal"
  },
  {
    "key": "granola-relay:fetch-notes:GranolaNote",
    "provider": "granola-relay",
    "sync": "fetch-notes",
    "model": "GranolaNote"
  },
  {
    "key": "granola-relay:fetch-folders:GranolaFolder",
    "provider": "granola-relay",
    "sync": "fetch-folders",
    "model": "GranolaFolder"
  },
  {
    "key": "recall-relay:fetch-recordings:RecallRecording",
    "provider": "recall-relay",
    "sync": "fetch-recordings",
    "model": "RecallRecording"
  },
  {
    "key": "recall-relay:fetch-transcripts:RecallTranscript",
    "provider": "recall-relay",
    "sync": "fetch-transcripts",
    "model": "RecallTranscript"
  },
  {
    "key": "hubspot-relay:fetch-companies:Company",
    "provider": "hubspot-relay",
    "sync": "fetch-companies",
    "model": "Company"
  },
  {
    "key": "hubspot-relay:fetch-contacts:Contact",
    "provider": "hubspot-relay",
    "sync": "fetch-contacts",
    "model": "Contact"
  },
  {
    "key": "hubspot-relay:fetch-deals:Deal",
    "provider": "hubspot-relay",
    "sync": "fetch-deals",
    "model": "Deal"
  },
  {
    "key": "hubspot-relay:fetch-orders:Order",
    "provider": "hubspot-relay",
    "sync": "fetch-orders",
    "model": "Order"
  },
  {
    "key": "hubspot-relay:fetch-products:Product",
    "provider": "hubspot-relay",
    "sync": "fetch-products",
    "model": "Product"
  },
  {
    "key": "hubspot-relay:fetch-users:User",
    "provider": "hubspot-relay",
    "sync": "fetch-users",
    "model": "User"
  },
  {
    "key": "hubspot-relay:fetch-tickets:Ticket",
    "provider": "hubspot-relay",
    "sync": "fetch-tickets",
    "model": "Ticket"
  },
  {
    "key": "docker_hub-composio-relay:fetch-repositories:DockerHubRepository",
    "provider": "docker_hub-composio-relay",
    "sync": "fetch-repositories",
    "model": "DockerHubRepository"
  },
  {
    "key": "docker_hub-composio-relay:fetch-tags:DockerHubTag",
    "provider": "docker_hub-composio-relay",
    "sync": "fetch-tags",
    "model": "DockerHubTag"
  },
  {
    "key": "docker_hub-composio-relay:fetch-webhooks:DockerHubWebhook",
    "provider": "docker_hub-composio-relay",
    "sync": "fetch-webhooks",
    "model": "DockerHubWebhook"
  },
  {
    "key": "reddit-composio-relay:fetch-subreddits:RedditTrackedSubreddit",
    "provider": "reddit-composio-relay",
    "sync": "fetch-subreddits",
    "model": "RedditTrackedSubreddit"
  },
  {
    "key": "reddit-composio-relay:fetch-posts:RedditPost",
    "provider": "reddit-composio-relay",
    "sync": "fetch-posts",
    "model": "RedditPost"
  },
  {
    "key": "reddit-composio-relay:fetch-hot-posts:RedditHotPost",
    "provider": "reddit-composio-relay",
    "sync": "fetch-hot-posts",
    "model": "RedditHotPost"
  },
  {
    "key": "reddit-composio-relay:fetch-rising-posts:RedditRisingPost",
    "provider": "reddit-composio-relay",
    "sync": "fetch-rising-posts",
    "model": "RedditRisingPost"
  },
  {
    "key": "reddit-composio-relay:fetch-top-posts:RedditTopPost",
    "provider": "reddit-composio-relay",
    "sync": "fetch-top-posts",
    "model": "RedditTopPost"
  },
  {
    "key": "reddit-composio-relay:fetch-best-posts:RedditBestPost",
    "provider": "reddit-composio-relay",
    "sync": "fetch-best-posts",
    "model": "RedditBestPost"
  },
  {
    "key": "fathom-relay:fetch-meetings:FathomMeeting",
    "provider": "fathom-relay",
    "sync": "fetch-meetings",
    "model": "FathomMeeting"
  },
  {
    "key": "fathom-relay:fetch-recording-summaries:FathomRecordingSummary",
    "provider": "fathom-relay",
    "sync": "fetch-recording-summaries",
    "model": "FathomRecordingSummary"
  },
  {
    "key": "fathom-relay:fetch-recording-transcripts:FathomRecordingTranscript",
    "provider": "fathom-relay",
    "sync": "fetch-recording-transcripts",
    "model": "FathomRecordingTranscript"
  },
  {
    "key": "fathom-relay:fetch-teams:FathomTeam",
    "provider": "fathom-relay",
    "sync": "fetch-teams",
    "model": "FathomTeam"
  },
  {
    "key": "fathom-relay:fetch-team-members:FathomTeamMember",
    "provider": "fathom-relay",
    "sync": "fetch-team-members",
    "model": "FathomTeamMember"
  },
  {
    "key": "dropbox-relay:fetch-files:DropboxFile",
    "provider": "dropbox-relay",
    "sync": "fetch-files",
    "model": "DropboxFile"
  },
  {
    "key": "dropbox-relay:fetch-folders:DropboxFolder",
    "provider": "dropbox-relay",
    "sync": "fetch-folders",
    "model": "DropboxFolder"
  },
  {
    "key": "dropbox-relay:fetch-shared-folders:DropboxSharedFolder",
    "provider": "dropbox-relay",
    "sync": "fetch-shared-folders",
    "model": "DropboxSharedFolder"
  },
  {
    "key": "dropbox-relay:fetch-shared-links:DropboxSharedLink",
    "provider": "dropbox-relay",
    "sync": "fetch-shared-links",
    "model": "DropboxSharedLink"
  },
  {
    "key": "daytona-relay:fetch-usage:DaytonaUsage",
    "provider": "daytona-relay",
    "sync": "fetch-usage",
    "model": "DaytonaUsage"
  },
  {
    "key": "gcp-relay:fetch-cloud-run:GcpCloudRunService",
    "provider": "gcp-relay",
    "sync": "fetch-cloud-run",
    "model": "GcpCloudRunService"
  },
  {
    "key": "gcp-relay:fetch-monitoring-alerts:GcpMonitoringAlert",
    "provider": "gcp-relay",
    "sync": "fetch-monitoring-alerts",
    "model": "GcpMonitoringAlert"
  },
  {
    "key": "gcp-relay:fetch-billing:GcpBilling",
    "provider": "gcp-relay",
    "sync": "fetch-billing",
    "model": "GcpBilling"
  },
  {
    "key": "gcp-relay:fetch-error-groups:GcpErrorGroup",
    "provider": "gcp-relay",
    "sync": "fetch-error-groups",
    "model": "GcpErrorGroup"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareWorkerScript",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareWorkerScript"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflarePagesProject",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflarePagesProject"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareD1Database",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareD1Database"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareKvNamespace",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareKvNamespace"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareR2Bucket",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareR2Bucket"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareQueue",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareQueue"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareTunnel",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareTunnel"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareNotificationWebhook",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareNotificationWebhook"
  },
  {
    "key": "cloudflare-relay:fetch-account-topology:CloudflareNotificationPolicy",
    "provider": "cloudflare-relay",
    "sync": "fetch-account-topology",
    "model": "CloudflareNotificationPolicy"
  },
  {
    "key": "cloudflare-relay:fetch-zone-topology:CloudflareZone",
    "provider": "cloudflare-relay",
    "sync": "fetch-zone-topology",
    "model": "CloudflareZone"
  },
  {
    "key": "cloudflare-relay:fetch-zone-topology:CloudflareDnsRecord",
    "provider": "cloudflare-relay",
    "sync": "fetch-zone-topology",
    "model": "CloudflareDnsRecord"
  },
  {
    "key": "cloudflare-relay:fetch-workers-usage:CloudflareWorkerUsage",
    "provider": "cloudflare-relay",
    "sync": "fetch-workers-usage",
    "model": "CloudflareWorkerUsage"
  },
  {
    "key": "neon-relay:fetch-topology:NeonOrganization",
    "provider": "neon-relay",
    "sync": "fetch-topology",
    "model": "NeonOrganization"
  },
  {
    "key": "neon-relay:fetch-topology:NeonProject",
    "provider": "neon-relay",
    "sync": "fetch-topology",
    "model": "NeonProject"
  },
  {
    "key": "neon-relay:fetch-topology:NeonBranch",
    "provider": "neon-relay",
    "sync": "fetch-topology",
    "model": "NeonBranch"
  },
  {
    "key": "neon-relay:fetch-topology:NeonEndpoint",
    "provider": "neon-relay",
    "sync": "fetch-topology",
    "model": "NeonEndpoint"
  },
  {
    "key": "neon-relay:fetch-topology:NeonSpendingLimit",
    "provider": "neon-relay",
    "sync": "fetch-topology",
    "model": "NeonSpendingLimit"
  },
  {
    "key": "neon-relay:fetch-operations:NeonOperation",
    "provider": "neon-relay",
    "sync": "fetch-operations",
    "model": "NeonOperation"
  },
  {
    "key": "neon-relay:fetch-consumption:NeonProjectConsumption",
    "provider": "neon-relay",
    "sync": "fetch-consumption",
    "model": "NeonProjectConsumption"
  },
  {
    "key": "neon-relay:fetch-consumption:NeonBranchConsumption",
    "provider": "neon-relay",
    "sync": "fetch-consumption",
    "model": "NeonBranchConsumption"
  },
  {
    "key": "neon-relay:fetch-advisor-issues:NeonAdvisorIssue",
    "provider": "neon-relay",
    "sync": "fetch-advisor-issues",
    "model": "NeonAdvisorIssue"
  }
] as const;

export type GeneratedNangoProviderModelEntry =
  (typeof GENERATED_NANGO_PROVIDER_MODEL_REGISTRY)[number];

export type GeneratedNangoProviderModel =
  GeneratedNangoProviderModelEntry["key"];

