export const LEGACY_TOOL_NAME_ALIASES = {
  create_workspace: 'workspace.create',
  set_workspace_key: 'workspace.set_key',
  register: 'agent.register',
  list_agents: 'agent.list',
  list_workspaces: 'workspace.list',
  join_workspace: 'workspace.join',
  switch_workspace: 'workspace.switch',
  create_channel: 'channel.create',
  list_channels: 'channel.list',
  join_channel: 'channel.join',
  leave_channel: 'channel.leave',
  invite_to_channel: 'channel.invite',
  set_channel_topic: 'channel.set_topic',
  archive_channel: 'channel.archive',
  post_message: 'message.post',
  get_messages: 'message.list',
  reply_to_thread: 'message.reply',
  get_thread: 'message.get_thread',
  send_dm: 'message.dm.send',
  get_dms: 'message.dm.list',
  send_group_dm: 'message.dm.send_group',
  add_reaction: 'message.reaction.add',
  remove_reaction: 'message.reaction.remove',
  search_messages: 'message.search',
  check_inbox: 'message.inbox.check',
  mark_read: 'message.inbox.mark_read',
  get_readers: 'message.inbox.get_readers',
  upload_file: 'message.file.upload',
  create_webhook: 'integration.webhook.create',
  list_webhooks: 'integration.webhook.list',
  delete_webhook: 'integration.webhook.delete',
  trigger_webhook: 'integration.webhook.trigger',
  create_subscription: 'integration.subscription.create',
  list_subscriptions: 'integration.subscription.list',
  get_subscription: 'integration.subscription.get',
  delete_subscription: 'integration.subscription.delete',
  register_action: 'integration.action.register',
  list_actions: 'integration.action.list',
  get_action: 'integration.action.get',
  delete_action: 'integration.action.delete',
  invoke_action: 'integration.action.invoke',
  complete_action: 'integration.action.complete',
  get_action_invocation: 'integration.action.get_invocation',
  add_agent: 'agent.add',
  remove_agent: 'agent.remove',
  // v0.5 two-level aliases
  'dm.send': 'message.dm.send',
  'dm.list': 'message.dm.list',
  'dm.send_group': 'message.dm.send_group',
  'reaction.add': 'message.reaction.add',
  'reaction.remove': 'message.reaction.remove',
  'inbox.check': 'message.inbox.check',
  'inbox.mark_read': 'message.inbox.mark_read',
  'inbox.get_readers': 'message.inbox.get_readers',
  'file.upload': 'message.file.upload',
  // v0.5 two-level aliases for programmability tools
  'webhook.create': 'integration.webhook.create',
  'webhook.list': 'integration.webhook.list',
  'webhook.delete': 'integration.webhook.delete',
  'webhook.trigger': 'integration.webhook.trigger',
  'subscription.create': 'integration.subscription.create',
  'subscription.list': 'integration.subscription.list',
  'subscription.get': 'integration.subscription.get',
  'subscription.delete': 'integration.subscription.delete',
  'action.register': 'integration.action.register',
  'action.list': 'integration.action.list',
  'action.get': 'integration.action.get',
  'action.delete': 'integration.action.delete',
  'action.invoke': 'integration.action.invoke',
  'action.complete': 'integration.action.complete',
  'action.get_invocation': 'integration.action.get_invocation',
} as const satisfies Record<string, string>;

export function resolveToolName(toolName: string): string {
  return LEGACY_TOOL_NAME_ALIASES[toolName as keyof typeof LEGACY_TOOL_NAME_ALIASES] ?? toolName;
}
