export const LEGACY_TOOL_NAME_ALIASES = {
  create_workspace: 'workspace.create',
  set_workspace_key: 'workspace.set_key',
  register: 'agent.register',
  list_agents: 'agent.list',
  list_workspaces: 'workspace.list',
  join_workspace: 'workspace.join',
  switch_workspace: 'workspace.switch',
  create_channel: 'channel.create',
  list_channels: 'channel.list',
  join_channel: 'channel.join',
  leave_channel: 'channel.leave',
  invite_to_channel: 'channel.invite',
  set_channel_topic: 'channel.set_topic',
  archive_channel: 'channel.archive',
  post_message: 'message.post',
  get_messages: 'message.list',
  reply_to_thread: 'message.reply',
  get_thread: 'message.get_thread',
  send_dm: 'dm.send',
  get_dms: 'dm.list',
  send_group_dm: 'dm.send_group',
  add_reaction: 'reaction.add',
  remove_reaction: 'reaction.remove',
  search_messages: 'message.search',
  check_inbox: 'inbox.check',
  mark_read: 'inbox.mark_read',
  get_readers: 'inbox.get_readers',
  upload_file: 'file.upload',
  create_webhook: 'webhook.create',
  list_webhooks: 'webhook.list',
  delete_webhook: 'webhook.delete',
  trigger_webhook: 'webhook.trigger',
  create_subscription: 'subscription.create',
  list_subscriptions: 'subscription.list',
  get_subscription: 'subscription.get',
  delete_subscription: 'subscription.delete',
  register_command: 'command.register',
  list_commands: 'command.list',
  delete_command: 'command.delete',
  invoke_command: 'command.invoke',
  add_agent: 'agent.add',
  remove_agent: 'agent.remove',
} as const satisfies Record<string, string>;

export function resolveToolName(toolName: string): string {
  return LEGACY_TOOL_NAME_ALIASES[toolName as keyof typeof LEGACY_TOOL_NAME_ALIASES] ?? toolName;
}
